### ISSUE TITLE
invalid multibyte char (US-ASCII) (SyntaxError)

### ISSUE THREAD

**Issue by donatoaz** [hisea/devise-bootstrap-views#18]
There seems to be some sort of encoding issue with the devise_bootstrap_views_helper.rb file.

I had to manually add:

  #!/bin/env ruby
  # encoding: utf-8

To the top of the file to get it to work.

rails 4.0.2
ruby ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-darwin10.8.0]

**Comment by isseu** [comment]
I have the same problem

**Comment by crab-apple** [comment]
I too have the same problem. It seems to be caused by the "cross character" (⨉) in this line:

``` html
<button type="button" class="close" data-dismiss="alert">⨉</button>
```

**Comment by PFischbeck** [comment]
This seems to be fixed by the PRs #22 and #23, but we will have to wait until the next release in order to receive the patch. Until then, this will be broken on Ruby 1.9.

**Comment by hisea** [comment]
Sorry for the delay but just made a release. now 0.0.6 should contain the unicode fix.

**Comment by PFischbeck** [comment]
Thanks!

**Comment by isseu** [comment]
Thanks!
