### ISSUE TITLE
Can we use git git submodules for locales?

### ISSUE THREAD

**Issue by mabras** [hisea/devise-bootstrap-views#37]
The [`devise-i18n`](https://github.com/tigrish/devise-i18n) gem has all the [locales files](https://github.com/tigrish/devise-i18n/tree/master/rails/locales) we need. So if we use git submodules for the locales you can centralize them in one place and no need to update them in two different places anymore.

**Comment by mabras** [comment]
Please @hisea can we make this? Do you want me send a pull request?

**Comment by hisea** [comment]
sure, please go ahead if you want to do a PR.
