### ISSUE TITLE
Lowercasing model name does not work in all languages

### ISSUE THREAD

**Issue by mpm** [hisea/devise-bootstrap-views#44]
Currently the model name is lowercased to create the summary sentence

> 2 errors prevent <model> from beeing saved

``` ruby
sentence = I18n.t('errors.messages.not_saved',
        count: resource.errors.count,
        resource: resource.class.model_name.human.downcase)
        resource: resource.class.model_name.human)
```

This does not work in German, where nouns are capitalized.

Originally I created this [little commit to fix this](https://github.com/mpm/devise-bootstrap-views/commit/dc350a1c513b43e9afc7642d59c46162fdb48ed5), thinking uppercase or lowercase spelling should just be controlled by the translations.

However, I found out that `.model_name.human` always capitalizes the translated model name, so with my fix we would end up with capitalized words in English, too (probably undesired).

Any ideas how to deal with this? A possible solution would be to gather the translated model names directly (instead of using `.model_name.human`), but this looks rather hacky to me.

Is nobody else bothered by this? To me, showing the model name lowercased in German just looks really wrong, like a quickly typed email with no uppercase letters at all.

**Comment by mkummer** [comment]
+1
I fully agree, this is bothering me, too!

**Comment by dankimio** [comment]
Locales are now taken directly from [devise-i18n](https://github.com/tigrish/devise-i18n), so it should be displayed correctly.
