### ISSUE TITLE
Change of view paths makes Rails not find correct translations

### ISSUE THREAD

**Issue by mvz** [hisea/devise-bootstrap-views#49]
With #48, using devise-bootstrap-views without copying the templates with the view generator no longer works: Devise expects the views to be in `views/devise` and now they're in `views/erb`. This means Devise' default views are used instead.

**Comment by dankimio** [comment]
Try adding `gem 'devise-bootstrap-views'` to the end of your Gemfile.

**Comment by mvz** [comment]
That makes no difference unfortunately. With 0.0.9, the template `devise-bootstrap-views-0.0.9/app/views/devise/sessions/new.html.erb` is rendered. With 0.0.10, the template `devise-4.2.0/app/views/devise/sessions/new.html.erb` is rendered.

**Comment by dankimio** [comment]
Haml and Slim are now generated separatly (https://github.com/hisea/devise-bootstrap-views/commit/77974f5fa6865e04d4e7a262e3d389ef7527f1df). Should be working now.

**Comment by mvz** [comment]
Thanks, @dankimio!
