### ISSUE TITLE
Unlocking account through email link does not work

### ISSUE THREAD

**Issue by tomoyuki28jp** [hisea/devise-bootstrap-views#61]
https://github.com/hisea/devise-bootstrap-views/blob/986a2b516405715c9f51ed612b99f63d5757122f/app/views/erb/mailer/unlock_instructions.html.erb#L7

This line should be changes as following:

```
-<p><%= link_to t('.action', default: 'Unlock my account'), unlock_url(@resource, unlock_token: @resource.unlock_token, locale: I18n.locale) %></p>
+<p><%= link_to t('.action', default: 'Unlock my account'), unlock_url(@resource, unlock_token: @token, locale: I18n.locale) %></p>
```

ref1: https://stackoverflow.com/a/22641026
ref2: https://github.com/plataformatec/devise/issues/3559#issuecomment-94706867

My devise version is `4.4.3`.

**Comment by dankimio** [comment]
Resolved in https://github.com/hisea/devise-bootstrap-views/commit/3a812ca6c297609bb42199b88fd18776b186412e
