### ISSUE TITLE
Branch bootstrap4

### ISSUE THREAD

**Issue by imgarylai** [hisea/devise-bootstrap-views#65]
It might be good to still have a branch called `bootstrap4`. 

This gem was amazing that I used it in the very early stage. However, my services was down while auto scaling because the branch `bootstrap4` was deleted and could not be found. 

> It was called by using `gem 'devise-bootstrap-views', github: 'hisea/devise-bootstrap-views', branch: 'bootstrap4'` 

I have already fixed it and should be fine, but I don't know how many people have been using the same thing. I hope it never happens to anyone again. 

This is just my suggestion and I don't think this slightly change affects anything with the project itself. Nevertheless, it might save many (or several? ) people's time. 

Thank you for your works!

**Comment by dankimio** [comment]
Hi @imgarylai, thanks for the feedback! We have the `1.0.0.alpha1` version published on RubyGems, which should be the same.
