### ISSUE TITLE
bootstrap_devise_error_messages not working

### ISSUE THREAD

**Issue by julius-b** [hisea/devise-bootstrap-views#68]
when creating the views with `rails generate devise:views:bootstrap_templates`, the newly generated file _sessions/new.html.erb_ does not contain the error messages block (`<%= bootstrap_devise_error_messages! %>`) which is available in _registrations/new.html.erb_.

Therefore, when entering faulty data during login, the user isn't informed. The registration form does show the errors as expected.

I tried adding the block to the file, but it has no effect. I also followed the wiki entry about _izitoast_, but it doesn't work either. The only way I can see the errors is by using `<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>`, but then it's not inside the bootstrap error message box.

**Comment by emcmanus** [comment]
You'll want to restart your server after running the generator. I believe there is an initializer that checks for the presence of those views.
