### ISSUE TITLE
How to have a main devise custom layout with devise-bootstrap-views subviews?

### ISSUE THREAD

**Issue by benjaminb10** [hisea/devise-bootstrap-views#8]
Hi,

When I create a custom layout for devise regarding devis doc (https://github.com/plataformatec/devise/wiki/How-To:-Create-custom-layouts) all the bootstrap devise views are erased and the ugly default views are back.

Do you know a way to do have a main devise custom layout and keep devise-bootstrap-views subviews?

**Comment by almozavr** [comment]
@benjaminb10 I suppose you forgot to add bootstrap css asset dependencies to custom (admin) layout?
